/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RouteTreeImport } from './routes/routeTree'
import { Route as NotFoundRouteImport } from './routes/notFoundRoute'

// Create/Update Routes

const RouteTreeRoute = RouteTreeImport.update({
  id: '/routeTree',
  path: '/routeTree',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRouteRoute = NotFoundRouteImport.update({
  id: '/notFoundRoute',
  path: '/notFoundRoute',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notFoundRoute': {
      id: '/notFoundRoute'
      path: '/notFoundRoute'
      fullPath: '/notFoundRoute'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRoute
    }
    '/routeTree': {
      id: '/routeTree'
      path: '/routeTree'
      fullPath: '/routeTree'
      preLoaderRoute: typeof RouteTreeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/notFoundRoute': typeof NotFoundRouteRoute
  '/routeTree': typeof RouteTreeRoute
}

export interface FileRoutesByTo {
  '/notFoundRoute': typeof NotFoundRouteRoute
  '/routeTree': typeof RouteTreeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/notFoundRoute': typeof NotFoundRouteRoute
  '/routeTree': typeof RouteTreeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/notFoundRoute' | '/routeTree'
  fileRoutesByTo: FileRoutesByTo
  to: '/notFoundRoute' | '/routeTree'
  id: '__root__' | '/notFoundRoute' | '/routeTree'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NotFoundRouteRoute: typeof NotFoundRouteRoute
  RouteTreeRoute: typeof RouteTreeRoute
}

const rootRouteChildren: RootRouteChildren = {
  NotFoundRouteRoute: NotFoundRouteRoute,
  RouteTreeRoute: RouteTreeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/notFoundRoute",
        "/routeTree"
      ]
    },
    "/notFoundRoute": {
      "filePath": "notFoundRoute.tsx"
    },
    "/routeTree": {
      "filePath": "routeTree.ts"
    }
  }
}
ROUTE_MANIFEST_END */
